### ISSUE TITLE
Rasplex will not show any files in library

### ISSUE THREAD

**Issue by heimdaloz** [RasPlex/rasplex-installer#53] opened 2022-03-04 10:24 UTC
I have used my Rasplex without problems for years. My Windows server recently need hardware to be updated. The plex client on the server and my Smart TV work fine. I can connect my Rasplex version to my server using the pin, with no difficult. However all that I see is:
Search
Watch Later
Search
Watch Later
Search
Watch Later
Search
Watch Later
Search
Watch Later
Both my server and the Rasplex are at their latest versions.

**Comment by Risca** [comment] 2022-04-24 12:20
This is a duplicate of https://github.com/RasPlex/RasPlex/issues/645

**Closed as completed by Risca** 2022-04-24 12:20 UTC

**Comment by Cathaldub** [comment] 2022-05-04 14:20
@Risca 
I've the same issue, tried the new images with the updated certs from the #645 page, deleted the cached certificate on my server, etc and nothing works, Using the pi3b+ image
Sadly have to go to kodi with plex plugin which works

**Comment by Risca** [comment] 2022-05-04 17:24
This repo is for the RasPlex _installer_ . Please report any issues with RasPlex in the ticket I linked before
